version: 2

sources:
  - name: public  # nome do schema onde a tabela está
    tables:
      - name: stg_casos_covid  # nome da tabela real no banco

models:
  - name: stg_casos_transformado
    description: Tabela com dados limpos e sem duplicatas
