models:
  - name: stg_casos_transformado
    description: "Dados limpos da vacinação, sem duplicados"
    tests:
      - unique:
          column_name: _id
      - not_null:
          column_name: _id
      - not_null:
          column_name: data_vacinacao
