name: covid_elt_profile
version: '1.0'
config-version: 2

profile: covid_elt_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  covid_elt_project:
    +materialized: view
