version: 2

models:
  - name: qualidade_dados
    description: "Verifica valores nulos por coluna e total de _id duplicados"
    columns:
      - name: total_linhas
        description: "Total de registros"
      - name: _id_nulos
        description: "Total de registros com _id nulo"
      - name: ids_duplicados
        description: "Total de IDs duplicados"

  - name: colunas_vazias
    description: "Colunas com mais de 50% de valores vazios (string vazia '')"
    columns:
      - name: coluna
        description: "Nome da coluna da base de dados"
      - name: vazios
        description: "Quantidade de valores vazios nessa coluna"
      - name: percentual
        description: "Percentual de valores vazios em relação ao total"
